config/routes.rb
Rails.application.routes.draw do
  resources :urls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'accounts#index'
    resources :accounts

	get "/:short_url", to: "urls#show"

end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validate :check_url
  after_save :make_short_url


	def make_short_url
		puts "Id is #{self.id}"
		self.url.strip!
		self.url = self.url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
		self.url.slice!(-1) if self.url[-1] == "/"
		self.url = "http://#{self.url}"
		chars = ['0'..'9', 'A'..'Z', 'a'..'z'].map { |range| range.to_a }.flatten
		short = 6.times.map { chars.sample }.join
		Url.find_by_short_url(short).nil?
		update_column(:short_url, short)
		update_column(:url, self.url)
	end


	def check_url
		self.url.strip!
		self.url = self.url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
		self.url.slice!(-1) if self.url[-1] == "/"
		self.url = "http://#{self.url}"
		@url = Url.find_by_url(self.url)
		if @url.present?
			errors.add(:base, 'This url is already present in database you can use its short url ')
			return false
		else
			puts "New url"
		end
	end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

 

  def new
    Account.create(:name => "New set",:place => "Haryana")
    # @audit = Audit.find(params[:audit_id])
    # @area = Area.create(
    #   audit_id: @audit.id,
    #   week_days_count: @audit.week_days_count,
    #   weekend_days_count: @audit.weekend_days_count,
    #   week_days_hours: @audit.week_days_hours,
    #   weekend_days_hours: @audit.weekend_days_hours
    # )
  end


  def index
    @accounts = Account.all

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
      @url = Url.find_by_short_url(params[:short_url])
    # @url = Url.find(params[:short_url])
    redirect_to @url.url
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to root_path, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find_by_short_url(params[:short_url])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:short_url, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/accounts/_content.html.erb
<div class="form-group account-sections-wrap" data-behavior="account-item" data-id="<%= account.id %>">

<div class="cont-group">
  <div class="hours-account-cont field-container">
    <%= text_field_tag "account[#{account.id}]name", account.name,
                        class: 'form-control input-default',
                        placeholder: 'account name',
                        'data-behavior' => 'input-account-name' %>
  </div>
  <div class="hours-account-cont field-container">
    <%= text_field_tag "account[#{account.id}]place", account.place,
                        class: 'form-control input-default',
                        placeholder: 'account place',
                        'data-behavior' => 'input-account-place' %>
  </div>
 
</div>

</div>

app/views/accounts/index.html.erb
<div class="form-container">
      <div>
        <div data-behavior="area-list">
          <% for area in @accounts %>
            <%= render 'accounts/content', account: area %>
            <br/>
          <% end %>
        </div>
      </div>

      <div class="add-action">
        <%= link_to ' + Add New Section', new_account_path,
                    remote: true,
                    class: 'btn btn-primary add-hours' %>
      </div>

      <div class="actions">
        <%= link_to "", class: 'btn btn-outline btn-primary' do %>
          Save &amp; Go to Replacement
        <% end %>
      </div>
    </div>

app/views/accounts/new.js.erb
    location.reload();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMultiple</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url, local: true) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Short url</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.short_url %></td>
        <td><%= url.url %></td>
        <td><%= link_to 'Visit Using Short Url', "#{root_url}/#{url.short_url}" , target: "blank"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short url:</strong>
  <%= @url.short_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @url.url %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>